### ISSUE TITLE
marvell-armhf: Azure pipeline master branch build failure

### ISSUE THREAD

**Issue by dflynn-Nokia** [Azure/sonic-buildimage#10070]
#### Description

The following master branch build error is consistently occurring in the  Azure.sonic-buildimage.official.marvell-armhf pipeline
This is a sonic-config-engine unittest failure.

2022-02-23T05:47:46.8539674Z ======================================================================
2022-02-23T05:47:46.8540138Z FAIL: test_buffers_dell6100_render_template (tests.test_j2files.TestJ2Files)
2022-02-23T05:47:46.8540787Z ----------------------------------------------------------------------
2022-02-23T05:47:46.8541209Z Traceback (most recent call last):
2022-02-23T05:47:46.8541922Z   File "/sonic/src/sonic-config-engine/tests/test_j2files.py", line 254, in test_buffers_dell6100_render_template
2022-02-23T05:47:46.8542896Z     self._test_buffers_render_template('dell', 'x86_64-dell_s6100_c2538-r0', 'Force10-S6100', 'sample-dell-6100-t0-minigraph.xml', 'buffers.json.j2', 'buffers-dell6100.json')
2022-02-23T05:47:46.8543819Z   File "/sonic/src/sonic-config-engine/tests/test_j2files.py", line 251, in _test_buffers_render_template
2022-02-23T05:47:46.8544319Z     assert filecmp.cmp(sample_output_file, self.output_file)
2022-02-23T05:47:46.8544674Z AssertionError
2022-02-23T05:47:46.8544808Z 
2022-02-23T05:47:46.8545335Z ----------------------------------------------------------------------
2022-02-23T05:47:46.8545728Z Ran 181 tests in 68.235s
2022-02-23T05:47:46.8545879Z 
2022-02-23T05:47:46.8546135Z FAILED (failures=1)
2022-02-23T05:47:46.8546517Z Test failed: <unittest.runner.TextTestResult run=181 errors=0 failures=1>

#### Steps to reproduce the issue:
1. Nightly marvell-armhf Azure pipeline build
2.
3.

#### Describe the results you received:
sonic-config-engine unittest failure leading to master branch build failure

#### Describe the results you expected:
successful master branch build for marvell-armhf

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by sachinv-msft** [comment]
@yxieca to provide reviewer's for this issue

**Comment by saiarcot895** [comment]
I believe #10132 should resolve this.

**Comment by dflynn-Nokia** [comment]
It looks like this did not fix the problem.

https://dev.azure.com/mssonic/build/_build/results?buildId=77524&view=logs&j=268525a4-f0a8-5106-2898-2602f02ebdb0&t=59457689-49a2-5da2-bad6-5355ff2da0c7

**Comment by dflynn-Nokia** [comment]
Issue is now fixed.
