### ISSUE TITLE
The member ports of portchannel can still forward traffic when the portchannel is down

### ISSUE THREAD

**Issue by leoli-nps** [Azure/sonic-buildimage#1771]
**Description**
I successfully configured PortChannel0001 between the two devices using two physical links. The related configuration is as follows:
```
    "PORT": {
        "Ethernet48": {
            "alias": "Ethernet49/1",
            "lanes": "80",
            "speed": "10000",
            "index": "48"
        },
        "Ethernet49": {
            "alias": "Ethernet50/1",
            "lanes": "81",
            "speed": "10000",
            "index": "49"
        },
        "Ethernet50": {
            "alias": "Ethernet51/1",
            "lanes": "82",
            "speed": "10000",
            "index": "50"
        }
    }
    "PORTCHANNEL": {
        "PortChannel0001": {
            "members": [
                "Ethernet48",
                "Ethernet49"
            ]
        }
    },
    "VLAN_MEMBER": {
        "Vlan17|PortChannel0001": {
            "tagging_mode": "untagged"
        },
        "Vlan17|Ethernet50": {
            "tagging_mode": "untagged"
        }
    },
    "VLAN": {
        "Vlan17": {
            "vlanid": "17"
        }
    }
```
When I disconnected one of the links, PortChannel0001 went down, but the other link still forwarded traffic. The following is the operation process(Use # as a comment prompt).
```
#(PortChannel0001 still up)

admin@switch100:~$ teamshow
Flags: A - active, I - inactive, Up - up, Dw - Down, N/A - not available, S - selected, D - deselected
  No.  Team Dev         Protocol     Ports
-----  ---------------  -----------  ---------------------------
 0001  PortChannel0001  LACP(A)(Up)  Ethernet49(S) Ethernet48(S)
admin@switch100:~$

#(Traffic is forwarded through two ports)

admin@switch100:~$ portstat
Last cached time was 2018-06-06 02:48:14.545146
          IFACE    STATE    RX_OK       RX_BPS    RX_UTIL    RX_ERR    RX_DRP    RX_OVR    TX_OK      TX_BPS    TX_UTIL    TX_ERR    TX_DRP    TX_OVR
---------------  -------  -------  -----------  ---------  --------  --------  --------  -------  ----------  ---------  --------  --------  --------
      Ethernet0        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet1        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet2        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet3        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet4        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet5        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet6        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet7        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet8        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet9        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet10        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet11        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet12        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet13        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet14        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet15        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet16        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet17        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet18        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet19        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet20        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet21        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet22        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet23        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet24        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet25        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet26        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet27        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet28        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet29        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet30        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet31        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet32        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet33        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet34        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet35        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet36        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet37        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet38        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet39        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet40        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet41        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet42        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet43        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet44        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet45        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet46        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet47        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet48        U    5,004  5785.46 B/s      0.00%         0         0       N/A        4   13.29 B/s      0.00%         0         0       N/A
     Ethernet49        U    5,002  5783.15 B/s      0.00%         0         0       N/A        4   13.29 B/s      0.00%         0         0       N/A
     Ethernet50        U        0     0.00 B/s      0.00%         0         0       N/A   10,002  11.29 KB/s      0.00%         0         0       N/A
     Ethernet51        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet52        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet53        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet54        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet55        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet56        X        0     0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
PortChannel0001      N/A      N/A          N/A        N/A       N/A       N/A       N/A      N/A         N/A        N/A       N/A       N/A       N/A
admin@switch100:~$ 

#(link failure)

admin@switch100:~$ show interfaces status Ethernet49
Command: intfutil status Ethernet49
  Interface    Lanes    Speed    MTU         Alias    Oper    Admin
-----------  -------  -------  -----  ------------  ------  -------
 Ethernet49       81      10G   9100  Ethernet50/1    down       up
admin@switch100:~$

#(PortChannel0001 down)

admin@switch100:~$ teamshow
Flags: A - active, I - inactive, Up - up, Dw - Down, N/A - not available, S - selected, D - deselected
  No.  Team Dev         Protocol     Ports
-----  ---------------  -----------  ---------------------------
 0001  PortChannel0001  LACP(A)(Dw)  Ethernet49(D) Ethernet48(S)
admin@switch100:~$

#(Traffic is still being forwarded through another port)

admin@switch100:~$ portstat
Last cached time was 2018-06-06 02:50:16.711588
          IFACE    STATE    RX_OK      RX_BPS    RX_UTIL    RX_ERR    RX_DRP    RX_OVR    TX_OK      TX_BPS    TX_UTIL    TX_ERR    TX_DRP    TX_OVR
---------------  -------  -------  ----------  ---------  --------  --------  --------  -------  ----------  ---------  --------  --------  --------
      Ethernet0        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet1        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet2        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet3        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet4        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet5        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet6        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet7        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet8        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
      Ethernet9        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet10        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet11        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet12        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet13        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet14        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet15        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet16        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet17        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet18        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet19        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet20        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet21        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet22        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet23        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet24        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet25        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet26        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet27        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet28        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet29        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet30        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet31        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet32        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet33        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet34        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet35        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet36        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet37        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet38        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet39        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet40        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet41        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet42        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet43        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet44        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet45        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet46        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet47        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet48        U   10,002  44.71 KB/s      0.00%         0         0       N/A        1    9.15 B/s      0.00%         0         0       N/A
     Ethernet49        D        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet50        U        0    0.00 B/s      0.00%         0         0       N/A   10,000  44.69 KB/s      0.00%         0         0       N/A
     Ethernet51        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet52        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet53        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet54        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet55        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
     Ethernet56        X        0    0.00 B/s      0.00%         0         0       N/A        0    0.00 B/s      0.00%         0         0       N/A
PortChannel0001      N/A      N/A         N/A        N/A       N/A       N/A       N/A      N/A         N/A        N/A       N/A       N/A       N/A
admin@switch100:~$ 
```

**Steps to reproduce the issue:**
1.As described in "Description".
2.
3.

**Describe the results you received:**
As described in "Description".

**Describe the results you expected:**
When the PortChannel goes down, its member ports should not forward traffic.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
admin@switch100:~$ show version
SONiC Software Version: SONiC.201803.0-dirty-20180510.051907
Distribution: Debian 8.10
Kernel: 3.16.0-5-amd64
Build commit: 1dd26fe
Build date: Thu May 10 05:35:51 UTC 2018
Built by: simon@debian89

Docker images:
REPOSITORY                 TAG                              IMAGE ID            SIZE
docker-syncd-nephos        201803.0-dirty-20180510.051907   d740eeeac60d        319.6 MB
docker-syncd-nephos        latest                           d740eeeac60d        319.6 MB
docker-orchagent-nephos    201803.0-dirty-20180510.051907   b1cf7aedb0ea        290.7 MB
docker-orchagent-nephos    latest                           b1cf7aedb0ea        290.7 MB
docker-dhcp-relay          201803.0-dirty-20180510.051907   cf16ce48da3f        285.2 MB
docker-dhcp-relay          latest                           cf16ce48da3f        285.2 MB
docker-database            201803.0-dirty-20180510.051907   d65afb7f3be5        285.2 MB
docker-database            latest                           d65afb7f3be5        285.2 MB
docker-snmp-sv2            201803.0-dirty-20180510.051907   29ea5346df9d        323 MB
docker-snmp-sv2            latest                           29ea5346df9d        323 MB
docker-teamd               201803.0-dirty-20180510.051907   a07ea8d2781f        290.5 MB
docker-teamd               latest                           a07ea8d2781f        290.5 MB
docker-router-advertiser   201803.0-dirty-20180510.051907   77904de1774b        282.8 MB
docker-router-advertiser   latest                           77904de1774b        282.8 MB
docker-platform-monitor    201803.0-dirty-20180510.051907   63445adc75bb        304.8 MB
docker-platform-monitor    latest                           63445adc75bb        304.8 MB
docker-lldp-sv2            201803.0-dirty-20180510.051907   1c66277f9e10        303.6 MB
docker-lldp-sv2            latest                           1c66277f9e10        303.6 MB
docker-fpm-quagga          201803.0-dirty-20180510.051907   a0584bb3cf43        297.1 MB
docker-fpm-quagga          latest                           a0584bb3cf43        297.1 MB
```

    **Attach debug file `sudo generate_dump`:**

[sonic_dump_switch100_20180606_025924.tar.gz](https://github.com/Azure/sonic-buildimage/files/2074733/sonic_dump_switch100_20180606_025924.tar.gz)

**Comment by stcheng** [comment]
https://github.com/Azure/sonic-buildimage/blob/master/src/libteam/patch/0006-teamd-Administratively-shutdown-port-channel-has-mem.patch

this is fixed! 😆

**Comment by leoli-nps** [comment]
@stcheng , This patch only resolves issue [#2066](https://github.com/Azure/sonic-buildimage/issues/2066), but the problems in this bug are still not resolved. In this bug, although the portchannel's operator state is down, its admin state is still up. Please check!
