### ISSUE TITLE
Deb9 SONiC image work on Accton Wedge100bf_65x, it have many issues.

### ISSUE THREAD

**Issue by robert1030** [Azure/sonic-buildimage#3206]
**Description**
issue1: Deb9 SONiC image work on Wedge100bf_65x , it's interface port 65 will be disappear (But bf-201807 release work on Wedge100bf_65x, it's interface port 65 is normally), Ethernet256 is interface port 65.

issue2: "show platform psustatus", it print error message on console screen.

issue3: "show platform syseeprom", it print error message on console screen.

issue4: Plug in qsfp28 module and fiber cable to interfaces of Wedge100bg_65x, "show interfaces transceiver eeprom", it can't got any SFP EEPROM info.

Report these issues to Accton edge-core, Accton edge-core tell us, they don't help solve these issues, because SONiC image doesn't build from them.

**Steps to reproduce the issue:**
1. Download SONiC image from [https://sonic-jenkins.westus2.cloudapp.azure.com/job/barefoot/job/buildimage-bf-all/363/artifact/target/sonic-barefoot.bin](url)

2. To Install SONiC image via ONIE and then waiting DUT process Image installer.
3. Doing below commands
    **issue1** command "show interfaces status"
    **issue2** command "show platform psustatus"
    **issue3** command "show platform syseeprom"
    **issue4** command "show interfaces transceiver eeprom"
         
**Describe the results you received:**
**issue1:**
root@sonic:/home/admin# show interfaces status
  Interface            Lanes    Speed    MTU        Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  ---------------  -------  -----  -----------  ------  ------  -------  ------  ----------
  Ethernet0          0,1,2,3     100G   9100    Ethernet0  routed      up       up     N/A         N/A
  Ethernet4          4,5,6,7     100G   9100    Ethernet4  routed      up       up     N/A         N/A
  Ethernet8        8,9,10,11     100G   9100    Ethernet8  routed      up       up     N/A         N/A
 Ethernet12      12,13,14,15     100G   9100   Ethernet12  routed      up       up     N/A         N/A
 Ethernet16      16,17,18,19     100G   9100   Ethernet16  routed      up       up     N/A         N/A
 Ethernet20      20,21,22,23     100G   9100   Ethernet20  routed      up       up     N/A         N/A
 Ethernet24      24,25,26,27     100G   9100   Ethernet24  routed      up       up     N/A         N/A
 Ethernet28      28,29,30,31     100G   9100   Ethernet28  routed      up       up     N/A         N/A
 Ethernet32      32,33,34,35     100G   9100   Ethernet32  routed      up       up     N/A         N/A
 Ethernet36      36,37,38,39     100G   9100   Ethernet36  routed      up       up     N/A         N/A
 Ethernet40      40,41,42,43     100G   9100   Ethernet40  routed      up       up     N/A         N/A
 Ethernet44      44,45,46,47     100G   9100   Ethernet44  routed      up       up     N/A         N/A
 Ethernet48      48,49,50,51     100G   9100   Ethernet48  routed      up       up     N/A         N/A
 Ethernet52      52,53,54,55     100G   9100   Ethernet52  routed      up       up     N/A         N/A
 Ethernet56      56,57,58,59     100G   9100   Ethernet56  routed      up       up     N/A         N/A
 Ethernet60      60,61,62,63     100G   9100   Ethernet60  routed      up       up     N/A         N/A
 Ethernet64      64,65,66,67     100G   9100   Ethernet64  routed      up       up     N/A         N/A
 Ethernet68      68,69,70,71     100G   9100   Ethernet68  routed      up       up     N/A         N/A
 Ethernet72      72,73,74,75     100G   9100   Ethernet72  routed      up       up     N/A         N/A
 Ethernet76      76,77,78,79     100G   9100   Ethernet76  routed      up       up     N/A         N/A
 Ethernet80      80,81,82,83     100G   9100   Ethernet80  routed      up       up     N/A         N/A
 Ethernet84      84,85,86,87     100G   9100   Ethernet84  routed      up       up     N/A         N/A
 Ethernet88      88,89,90,91     100G   9100   Ethernet88  routed      up       up     N/A         N/A
 Ethernet92      92,93,94,95     100G   9100   Ethernet92  routed      up       up     N/A         N/A
 Ethernet96      96,97,98,99     100G   9100   Ethernet96  routed      up       up     N/A         N/A
Ethernet100  100,101,102,103     100G   9100  Ethernet100  routed      up       up     N/A         N/A
Ethernet104  104,105,106,107     100G   9100  Ethernet104  routed      up       up     N/A         N/A
Ethernet108  108,109,110,111     100G   9100  Ethernet108  routed      up       up     N/A         N/A
Ethernet112  112,113,114,115     100G   9100  Ethernet112  routed      up       up     N/A         N/A
Ethernet116  116,117,118,119     100G   9100  Ethernet116  routed      up       up     N/A         N/A
Ethernet120  120,121,122,123     100G   9100  Ethernet120  routed      up       up     N/A         N/A
Ethernet124  124,125,126,127     100G   9100  Ethernet124  routed      up       up     N/A         N/A
Ethernet128  128,129,130,131     100G   9100  Ethernet128  routed    down       up     N/A         N/A
Ethernet132  132,133,134,135     100G   9100  Ethernet132  routed    down       up     N/A         N/A
Ethernet136  136,137,138,139     100G   9100  Ethernet136  routed    down       up     N/A         N/A
Ethernet140  140,141,142,143     100G   9100  Ethernet140  routed    down       up     N/A         N/A
Ethernet144  144,145,146,147     100G   9100  Ethernet144  routed    down       up     N/A         N/A
Ethernet148  148,149,150,151     100G   9100  Ethernet148  routed    down       up     N/A         N/A
Ethernet152  152,153,154,155     100G   9100  Ethernet152  routed    down       up     N/A         N/A
Ethernet156  156,157,158,159     100G   9100  Ethernet156  routed    down       up     N/A         N/A
Ethernet160  160,161,162,163     100G   9100  Ethernet169  routed    down       up     N/A         N/A
Ethernet164  164,165,166,167     100G   9100  Ethernet164  routed    down       up     N/A         N/A
Ethernet168  168,169,170,171     100G   9100  Ethernet168  routed    down       up     N/A         N/A
Ethernet172  172,173,174,175     100G   9100  Ethernet172  routed    down       up     N/A         N/A
Ethernet176  176,177,178,179     100G   9100  Ethernet176  routed    down       up     N/A         N/A
Ethernet180  180,181,182,183     100G   9100  Ethernet180  routed    down       up     N/A         N/A
Ethernet184  184,185,186,187     100G   9100  Ethernet184  routed    down       up     N/A         N/A
Ethernet188  188,189,190,191     100G   9100  Ethernet188  routed    down       up     N/A         N/A
Ethernet192  192,193,194,195     100G   9100  Ethernet192  routed    down       up     N/A         N/A
Ethernet196  196,197,198,199     100G   9100  Ethernet196  routed    down       up     N/A         N/A
Ethernet200  200,201,202,203     100G   9100  Ethernet200  routed    down       up     N/A         N/A
Ethernet204  204,205,206,207     100G   9100  Ethernet204  routed    down       up     N/A         N/A
Ethernet208  208,209,210,211     100G   9100  Ethernet208  routed    down       up     N/A         N/A
Ethernet212  212,213,214,215     100G   9100  Ethernet212  routed    down       up     N/A         N/A
Ethernet216  216,217,218,219     100G   9100  Ethernet216  routed    down       up     N/A         N/A
Ethernet220  220,221,222,223     100G   9100  Ethernet220  routed    down       up     N/A         N/A
Ethernet224  224,225,226,227     100G   9100  Ethernet224  routed    down       up     N/A         N/A
Ethernet228  228,229,230,231     100G   9100  Ethernet228  routed    down       up     N/A         N/A
Ethernet232  232,233,234,235     100G   9100  Ethernet232  routed    down       up     N/A         N/A
Ethernet236  236,237,238,239     100G   9100  Ethernet236  routed    down       up     N/A         N/A
Ethernet240  240,241,242,243     100G   9100  Ethernet240  routed    down       up     N/A         N/A
Ethernet244  244,245,246,247     100G   9100  Ethernet244  routed    down       up     N/A         N/A
Ethernet248  248,249,250,251     100G   9100  Ethernet248  routed    down       up     N/A         N/A
Ethernet252  252,253,254,255     100G   9100  Etherner252  routed    down       up     N/A         N/A

**issue2:** error message
root@sonic:/home/admin# show platform psustatus 
Error! Failed to get the number of PSUs!
Error: fail to get psu status from state DB

**issue3:** error message
show platform syseeprom 
/usr/bin/decode-syseeprom : ERROR : cannot load module: /usr/share/sonic/device/x86_64-accton_wedge100bf_65x-r0/plugins/eeprom.py

**issue4:** error message
root@sonic:/home/admin# show platform syseeprom 
/usr/bin/decode-syseeprom : ERROR : cannot load module: /usr/share/sonic/device/x86_64-accton_wedge100bf_65x-r0/plugins/eeprom.py

root@sonic:/home/admin# show interfaces transceiver eeprom 
Ethernet0: SFP EEPROM Not detected

Ethernet4: SFP EEPROM Not detected

Ethernet8: SFP EEPROM Not detected

Ethernet12: SFP EEPROM Not detected

Ethernet16: SFP EEPROM Not detected

Ethernet20: SFP EEPROM Not detected

Ethernet24: SFP EEPROM Not detected

Ethernet28: SFP EEPROM Not detected

Ethernet32: SFP EEPROM Not detected

Ethernet36: SFP EEPROM Not detected

Ethernet40: SFP EEPROM Not detected

Ethernet44: SFP EEPROM Not detected

Ethernet48: SFP EEPROM Not detected
......
......
......

**Describe the results you expected:**
**issue1: show interfaces status @ bf-201807 release, Ethernet256 does't disappear**

root@wedge100bf:/home/admin# show interfaces status
  Interface            Lanes    Speed    MTU        Alias    Vlan    Oper    Admin    Type    
-----------  ---------------  -------  -----  -----------  ------  ------  -------  ------  
.....
.....
.....
Ethernet240  240,241,242,243     100G   9100  Ethernet240  routed    down       up     N/A 
Ethernet244  244,245,246,247     100G   9100  Ethernet244  routed    down       up     N/A 
Ethernet248  248,249,250,251     100G   9100  Ethernet248  routed    down       up     N/A 
Ethernet252  252,253,254,255     100G   9100  Etherner252  routed    down       up     N/A 
Ethernet256  256,257,258,259      40G   9100  Ethernet256  routed      up       up     N/A

**issue4:**
Interfaces status are up, it mean qsfp28 module and fiber cable can work with DUT, SFP EEPROM should be detected.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**
    show version

SONiC Software Version: SONiC.HEAD.363-dirty-20190722.082137
Distribution: Debian 9.9
Kernel: 4.9.0-9-2-amd64
Build commit: 40c8bc14
Build date: Mon Jul 22 10:10:13 UTC 2019
Built by: johnar@jenkins-worker-3

Platform: x86_64-accton_wedge100bf_65x-r0
HwSKU: mavericks
ASIC: barefoot
/usr/bin/decode-syseeprom : ERROR : cannot load module: /usr/share/sonic/device/x86_64-accton_wedge100bf_65x-r0/plugins/eeprom.py
Serial Number: 
Uptime: 06:58:10 up 4 min,  1 user,  load average: 0.74, 0.74, 0.36

Docker images:
REPOSITORY                 TAG                              IMAGE ID            SIZE
docker-syncd-bfn           HEAD.363-dirty-20190722.082137   e1e854d4cf96        3.53GB
docker-syncd-bfn           latest                           e1e854d4cf96        3.53GB
docker-lldp-sv2            HEAD.363-dirty-20190722.082137   d2f499c37e3d        298MB
docker-lldp-sv2            latest                           d2f499c37e3d        298MB
docker-router-advertiser   HEAD.363-dirty-20190722.082137   a89f8aec18f1        280MB
docker-router-advertiser   latest                           a89f8aec18f1        280MB
docker-dhcp-relay          HEAD.363-dirty-20190722.082137   f89423272ba6        288MB
docker-dhcp-relay          latest                           f89423272ba6        288MB
docker-database            HEAD.363-dirty-20190722.082137   2fe7f8a77d3b        280MB
docker-database            latest                           2fe7f8a77d3b        280MB
docker-teamd               HEAD.363-dirty-20190722.082137   165406b3e392        302MB
docker-teamd               latest                           165406b3e392        302MB
docker-snmp-sv2            HEAD.363-dirty-20190722.082137   6cdc66db0d2b        312MB
docker-snmp-sv2            latest                           6cdc66db0d2b        312MB
docker-orchagent           HEAD.363-dirty-20190722.082137   3c39b47fef12        320MB
docker-orchagent           latest                           3c39b47fef12        320MB
docker-fpm-frr             HEAD.363-dirty-20190722.082137   930f1a53a7fa        318MB
docker-fpm-frr             latest                           930f1a53a7fa        318MB
docker-sonic-telemetry     HEAD.363-dirty-20190722.082137   e99cd55c3cc1        303MB
docker-sonic-telemetry     latest                           e99cd55c3cc1        303MB
docker-platform-monitor    HEAD.363-dirty-20190722.082137   e455021dbecd        325MB
docker-platform-monitor    latest                           e455021dbecd        325MB

**Comment by akokhan** [comment]
Hi @robert1030 
Thank you for the detailed description of the issues! The issues #2 and #3 (psu & syseeprom) have been fixed starting from #372. We will check on issues #1 and #4 and get back to you.

**Comment by akokhan** [comment]
The PR as follows addresses the issue 4 (sfputil)
https://github.com/Azure/sonic-buildimage/pull/3324

**Comment by robert1030** [comment]
Hi akokhan

Thank you for your support.
issue1 still not be fixed after merge patch [#3324](https://github.com/Azure/sonic-buildimage/pull/3324) , because wedge100bf-65x that it has 65 ports, but Ethernet252 only mapping to 64port. the port 65 of wedge100bf-65x still keep disappear on [buildimage-bf-all #386](https://sonic-jenkins.westus2.cloudapp.azure.com/job/barefoot/job/buildimage-bf-all/386/artifact/target/sonic-barefoot.bin)

port 65 of wedge100bf-65x that it look like this on [buildimage-bf-201807 #18](https://sonic-jenkins.westus2.cloudapp.azure.com/job/barefoot/job/buildimage-bf-201807/lastSuccessfulBuild/artifact/target/sonic-barefoot.bin)

show interfaces status Ethernet252
  Interface            Lanes    Speed    MTU        Alias    Oper    Admin
-----------  ---------------  -------  -----  -----------  ------  -------
Ethernet252  252,253,254,255      N/A   1500  Ethernet252    down     down
root@switch:/home/admin# show interfaces status Ethernet256
  Interface            Lanes    Speed    MTU        Alias    Oper    Admin
-----------  ---------------  -------  -----  -----------  ------  -------
Ethernet256  256,257,258,259      N/A   1500  Ethernet256    down     down

show version
SONiC Software Version: SONiC.HEAD.18-0e0d678
Distribution: Debian 8.11
Kernel: 3.16.0-5-amd64
Build commit: 0e0d678
Build date: Thu Jul 11 01:36:21 UTC 2019
Built by: johnar@jenkins-worker-3

**Comment by akokhan** [comment]
Right, as I mentioned above, the issues 2,3,4 are fixed. The issue 1 is still WIP.

**Comment by robert1030** [comment]
Hi akokhan:
     thanks for your response, waiting issue 1 that it have a good news.

**Comment by akokhan** [comment]
The issue #1 expected to be fix once the following PR is merged https://github.com/Azure/sonic-buildimage/pull/3461

**Comment by robert1030** [comment]
These issues has be fixed, and check on SONiC.HEAD.437-dirty-20191005.065051
