### ISSUE TITLE
Unix socket /var/run/monit.sock connection error -- No such file or directory

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-buildimage#7024]
#### Steps to reproduce the issue:
1. https://dev.azure.com/mssonic/build/_build/results?buildId=6546&view=logs&j=551384a3-3c3d-5d98-9a93-ab579ce10658&t=dcc0ef7a-c27d-5084-36c2-e0f4d142c187
2.
3.

#### Output of `show version`:

```
(paste your output here)
```

**Comment by lguohan** [comment]
the regression is introduced by this pr https://github.com/Azure/sonic-utilities/pull/1471

**Comment by lguohan** [comment]
revert the pr #7025

**Comment by lguohan** [comment]
fixed by https://github.com/Azure/sonic-utilities/commit/4a0c0103c7dba820e4ab4aa2239b9a4437460b07

**Comment by theasianpianist** [comment]
Still seeing this issue on an image with the fix included, re-opening and update the issue description

**Comment by yozhao101** [comment]
@jleveque I talked with @theasianpianist and checked this issue. The root reason is that the image on device `str2-7050cx3-acs-10` did not include the PR https://github.com/Azure/sonic-utilities/pull/1543 which was used to fix this issue.

    admin@str2-7050cx3-acs-10:~$ show ver
    SONiC Software Version: SONiC.20201231.beta.17
    Distribution: Debian 10.9
    Kernel: 4.19.0-12-2-amd64
    Build commit: 2efb4ce682
    Build date: Tue Apr  6 01:13:55 UTC 2021
    Built by: sonicbld@new-worker-3
    
    Platform: x86_64-arista_7050cx3_32s
    HwSKU: Arista-7050CX3-32S-D48C8
    ASIC: broadcom
    ASIC Count: 1
    Serial Number: JPE20437840
    Uptime: 02:42:48 up 1 day,  7:13,  2 users,  load average: 4.40, 4.64, 4.53

    admin@str2-7050cx3-acs-10:~$ sudo config reload -y
    Caching ARP table to /host/config-reload
    Disabling container monitoring ...
    Stopping SONiC target ...
    Running command: /usr/local/bin/sonic-cfggen -j /etc/sonic/init_cfg.json -j /etc/sonic/config_db.json --write-to-db
    Running command: /usr/local/bin/db_migrator.py -o migrate
    Resetting failed status on bgp.service
    Resetting failed status on caclmgrd.service
    Resetting failed status on dhcp_relay.service
    Resetting failed status on hostcfgd.service
    Resetting failed status on hostname-config.service
    Resetting failed status on interfaces-config.service
    Resetting failed status on lldp.service
    Resetting failed status on ntp-config.service
    Resetting failed status on pmon.service
    Resetting failed status on procdockerstatsd.service
    Resetting failed status on radv.service
    Resetting failed status on rsyslog-config.service
    Resetting failed status on swss.service
    Resetting failed status on syncd.service
    Resetting failed status on teamd.service
    Resetting failed status on telemetry.timer
    Restarting SONiC target ...
    Reloading Monit configuration ...
    Reinitializing monit daemon
    Enabling container monitoring ...

**Comment by SavchukRomanLv** [comment]
@lguohan issue is still seen at master SONiC: 
SONiC Software Version: SONiC.master.172539-dirty-20221110.095210
Distribution: Debian 11.5
Kernel: 5.10.0-12-2-amd64
Build commit: 7c746e67d
Build date: Thu Nov 10 16:18:12 UTC 2022
Built by: AzDevOps@sonic-build-workers-002D7H

Platform: x86_64-arista_7170_64c
HwSKU: Arista-7170-64C
ASIC: barefoot
ASIC Count: 1
Serial Number: SGD19412115
Model Number: DCS-7170-64C
Hardware Revision: 02.00
Uptime: 13:37:45 up  4:25,  1 user,  load average: 0.84, 0.73, 0.78
Date: Mon 21 Nov 2022 13:37:45
