### ISSUE TITLE
Bullseye: DHCP relay test case fails with missing packets and zebra crash

### ISSUE THREAD

**Issue by saiarcot895** [Azure/sonic-buildimage#8474]
#### Description

On a Bullseye image, when running the `dhcp_relay/test_dhcp_relay.py` testcase on a kvm t0 topology, `zebra` crashes, with the following backtrace:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ff499a54535 in __GI_abort () at abort.c:79
#2  0x00007ff499a5440f in __assert_fail_base (fmt=0x7ff499bb6ee0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7ff4995624f1 "data_len", file=0x7ff499562074 "zebra/zebra_fpm.c", line=998, function=<optimized out>) at assert.c:92
#3  0x00007ff499a62102 in __GI___assert_fail (assertion=assertion@entry=0x7ff4995624f1 "data_len", file=file@entry=0x7ff499562074 "zebra/zebra_fpm.c", line=line@entry=998,
    function=function@entry=0x7ff499562c70 <__PRETTY_FUNCTION__.21844> "zfpm_build_route_updates") at assert.c:101
#4  0x00007ff499560dd2 in zfpm_build_route_updates () at zebra/zebra_fpm.c:998
#5  zfpm_build_updates () at zebra/zebra_fpm.c:1154
#6  zfpm_write_cb (thread=<optimized out>) at zebra/zebra_fpm.c:1191
#7  zfpm_write_cb (thread=0x7ffc1dcd2c10) at zebra/zebra_fpm.c:1162
#8  0x00007ff499dac516 in thread_call (thread=thread@entry=0x7ffc1dcd2c10) at lib/thread.c:1628
#9  0x00007ff499d74cf0 in frr_run (master=0x562209e7da10) at lib/libfrr.c:1099
#10 0x000056220880ed0d in main (argc=9, argv=0x7ffc1dcd3018) at zebra/main.c:457
```

In addition, the DHCP test case fails because it's unable to find the relay/offer packets.

#### Output of `show version`:

```
SONiC Software Version: SONiC.bullseye-upgrade-base.0-dirty-20210813.131217
Distribution: Debian 11.0
Kernel: 5.10.0-7-2-amd64
Build commit: 0487f6f66
Build date: Fri Aug 13 20:24:14 UTC 2021
Built by: sarcot@sarcot-dev-vm-01

Platform: x86_64-kvm_x86_64-r0
HwSKU: Force10-S6000
ASIC: vs
ASIC Count: 1
Serial Number: None
Model Number: None
Hardware Revision: None
Uptime: 22:50:24 up  1:55,  1 user,  load average: 0.51, 0.39, 0.32
```
#### Output of `show techsupport`:

[sonic_dump_vlab-01_20210813_222231.tar.gz](https://github.com/Azure/sonic-buildimage/files/6985483/sonic_dump_vlab-01_20210813_222231.tar.gz)

**Comment by lguohan** [comment]
the bug is fixed in #8443 , can you rebase your pr?

**Comment by saiarcot895** [comment]
Zebra isn't crashing anymore, so the switch is in a good state now, but DHCP packets are still not being received.
